---
- name: Install Essential Packages
  ansible.builtin.import_role:
    name: common
    tasks_from: install-packages
- name: Configure console and MOTD banners
  ansible.builtin.include_tasks: update_login_banners.yaml
