---
- name: Install Essential Packages
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/roles/common/tasks/install-packages.yaml"
- name: Configure console and MOTD banners
  ansible.builtin.include_tasks: update_login_banners.yaml
