---
- name: Linux Terminal Pre Login Info
  ansible.builtin.copy:
    dest: /etc/issue
    content: |
      ##########################################################################
      ##                                                                       #
      ##                     WELCOME TO \n!                                 
      ##                                                                       #
      ##########################################################################

      >> SYSTEM INFO <<
      ───────────────────────────────────────────────────────────────────────────
      OS               : \s \r (\v)
      Hostname         : \n
      Architecture     : \m
      TTY Line         : \l
      Baud Rate        : \b
      ───────────────────────────────────────────────────────────────────────────

      >> USER INFO <<
      ───────────────────────────────────────────────────────────────────────────
      Active           : \U
      Current Time     : \t
      Current Date     : \d
      ───────────────────────────────────────────────────────────────────────────

      ##########################################################################
      #                    ** WARNING: Unauthorized Access **                  #
      #                This system is for authorized users only.               #
      ##########################################################################
    owner: root
    group: root
    mode: "0744"
