---
- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Perform full upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
  when: ansible_facts['pkg_mgr'] == 'apt'
  check_mode: no # Package upgrades cannot run in dry-run

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
  changed_when: false

- name: Reboot if required
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: reboot_required.stat.exists and not ansible_check_mode

- name: Wait for node to be back online
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 300
  when: reboot_required.stat.exists and not ansible_check_mode

- name: Confirm update complete
  ansible.builtin.shell: uname -r
  register: kernel
  changed_when: false

- name: Show kernel version
  ansible.builtin.debug:
    msg: "Node {{ inventory_hostname }} running kernel {{ kernel.stdout }}"
