- name: Update Samba Configuration
  ansible.builtin.blockinfile:
    path: /etc/samba/smb.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - public"
    insertafter: EOF
    block: |
      [public]
      path = /share/public
      read only = no
      browsable = yes
      guest ok = yes
      force user = nobody
