---
- name: Linux Server Setup [HomeLab]
  hosts: linux
  become: true
  roles:
    - linuxserver
  vars:
    required_packages:
      - curl
      - rsync
  tags:
    - linux

- name: File share Setup
  hosts: samba
  become: true
  roles:
    - samba
  vars:
    required_packages:
      - samba
  tags:
    - samba
