---
- name: Linux Server Setup [HomeLab]
  hosts: server
  become: true
  roles:
    - linuxserver
  tags:
    - setup
    - linux

- name: Samba Server Setup
  hosts: samba
  become: true
  roles:
    - samba
  tags:
    - samba