---
- name: Linux Server Setup [HomeLab]
  hosts: linux
  become: true
  roles:
    - linuxserver
  vars:
    required_packages:
      - curl
      - rsync
  tags:
    - linux

- name: File share Setup
  hosts: samba
  become: true
  vars_files:
    - ../config/samba.yaml
  roles:
    - samba
  vars:
    required_packages:
      - samba
  tags:
    - samba

- name: Media Server Setup
  hosts: media
  become: true
  vars:
    media_transmission_rpc_password: "debian"
    media_transmission_download_dir: "/share/public/movies/transmission"
    required_packages:
      - transmission-daemon
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Apply media role if smbd service is running
      ansible.builtin.include_role:
        name: media
      when: >
        services['smbd'].state is defined and services['smbd'].state == 'running'
  tags:
    - media

# - name: Custom Linux package installs [nexus]
#   hosts: linux
#   become: true
#   tasks:
#     - name: Install custom misc packages
#       ansible.builtin.package:
#         name: "{{ item }}"
#         state: absent
#       loop:
#         - wsdd
#   tags: nexus
