name: Homelab Deployment

on:
  workflow_dispatch:
    inputs:
      role:
        description: "Select the role to run"
        required: true
        default: "setup"
        type: choice
        options:
          - setup
      dry_run:
        description: "Enable dry-run mode"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: [self-hosted, homelab]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Execute Ansible Playbook
        run: |
          ROLE="${{ github.event.inputs.role }}"
          DRY_RUN="${{ github.event.inputs.dry_run }}"

          echo "Selected role: $ROLE"
          if [ "$DRY_RUN" = "true" ]; then
            echo "Running in dry-run mode..."
            ansible-playbook ansible/site.yml -i ansible/inventory/hosts.yml --tags "$ROLE" --check --diff
          else
            echo "Executing role: $ROLE"
            ansible-playbook ansible/site.yml -i ansible/inventory/hosts.yml --tags "$ROLE"
          fi
