name: Homelab Manual Deployment

on:
  workflow_dispatch:
    inputs:
      role:
        description: "Role to run"
        required: true
        default: all
        type: choice
        options:
          - setup
          - maintenance
          - all
      dry_run:
        description: "Enable dry-run mode"
        required: false
        default: "false"

jobs:
  setup-role:
    name: Setup Role Deployment
    if: ${{ github.event.inputs.role == 'setup' || github.event.inputs.role == 'all' }}
    uses: shabhilash/homelab-ansible/.github/workflows/homelab-deployment.yml@main
    with:
      role: setup
      dry_run: "${{ github.event.inputs.dry_run }}"

  maintenance-role:
    name: Maintenance Role Deployment
    needs: setup-role
    if: ${{ github.event.inputs.role == 'maintenance' || github.event.inputs.role == 'all' }}
    uses: shabhilash/homelab-ansible/.github/workflows/homelab-deployment.yml@main
    with:
      role: maintenance
      dry_run: "${{ github.event.inputs.dry_run }}"
