name: Homelab Manual Deployment

on:
  workflow_dispatch:
    inputs:
      role:
        description: "Role to run"
        required: true
        default: maintenance
        type: choice
        options:
          - all
          - setup
          - maintenance
      dry_run:
        description: "Enable dry-run mode"
        required: false
        default: "false"

jobs:
  deploy:
    uses: shabhilash/homelab-ansible/.github/workflows/homelab-deployment.yml@main
    with:
      role: ${{ github.event.inputs.role }}
      dry_run: "${{ github.event.inputs.dry_run }}"
