name: Homelab Deployment

on:
  workflow_call:
    inputs:
      role:
        required: true
        type: string
      dry_run:
        required: false
        default: "false" # string, not boolean
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, homelab]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Execute Ansible Playbook
        run: |
          ROLE="${{ inputs.role }}"
          DRY_RUN="${{ inputs.dry_run }}"

          # Validate role
          VALID_ROLES=("setup" "update")
          if [[ ! " ${VALID_ROLES[@]} " =~ " $ROLE " ]]; then
            echo "ERROR: Invalid role: $ROLE"
            exit 1
          fi

          echo "Selected role: $ROLE"

          # Set dry-run flag
          DRY_RUN_FLAG=""
          if [ "$DRY_RUN" = "true" ]; then
            echo "Running in dry-run mode..."
            DRY_RUN_FLAG="--check"
          fi

          ansible-playbook playbooks/site.yml -i playbooks/inventory/hosts.yml --tags "$ROLE" $DRY_RUN_FLAG --diff
