name: Homelab Deployment

on:
  workflow_call:
    inputs:
      role:
        required: true
        type: string
      dry_run:
        required: false
        default: "false"
        type: string

jobs:
  execute-ansible-role:
    name: Execute Ansible Role
    runs-on: [self-hosted, homelab]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run Ansible Playbook
        run: |
          ROLE="${{ inputs.role }}"
          DRY_RUN="${{ inputs.dry_run }}"
          DRY_RUN_FLAG=""

          echo "Selected role: $ROLE"

          if [ "$DRY_RUN" = "true" ]; then
            echo "Running in dry-run mode..."
            DRY_RUN_FLAG="--check"
          fi

          echo "Executing Ansible role: $ROLE"
          ansible-playbook playbooks/site.yml -i playbooks/inventory/hosts.yml --tags "$ROLE" $DRY_RUN_FLAG --diff
